param(
    [string] $OutputPath,
    [switch] $NoWrite
)

$ErrorActionPreference = 'Stop'

function Get-MesocoHostIp {
    if ($env:MESOCO_HOST_IP -and $env:MESOCO_HOST_IP.Trim()) {
        return $env:MESOCO_HOST_IP.Trim()
    }

    $addresses = Get-NetIPAddress -AddressFamily IPv4 |
        Where-Object {
            $_.IPAddress -notlike '127.*' -and
            $_.IPAddress -notlike '169.254.*' -and
            $_.IPAddress -notlike '0.*' -and
            $_.AddressState -eq 'Preferred'
        } |
        ForEach-Object {
            $alias = $_.InterfaceAlias
            $score = 10

            if ($alias -match 'vEthernet|VMware|VirtualBox|Loopback|Radmin|Tailscale|ZeroTier') {
                $score = 20
            } elseif ($alias -match 'Wi-?Fi|Wireless|WLAN|Ethernet') {
                $score = 0
            }

            [PSCustomObject]@{
                IPAddress = $_.IPAddress
                InterfaceAlias = $alias
                InterfaceMetric = $_.InterfaceMetric
                Score = $score
            }
        } |
        Sort-Object Score, InterfaceMetric, InterfaceAlias, IPAddress

    $selected = $addresses | Select-Object -First 1

    if (-not $selected) {
        throw 'No usable LAN IPv4 address was found. Set MESOCO_HOST_IP manually, then run the script again.'
    }

    return $selected.IPAddress
}

$hostIp = Get-MesocoHostIp
$appUrl = "http://${hostIp}:8000"
$frontendUrl = "http://${hostIp}:5173"
$statefulDomains = @(
    'localhost',
    'localhost:8000',
    'localhost:5173',
    '127.0.0.1',
    '127.0.0.1:8000',
    '127.0.0.1:5173',
    $hostIp,
    "${hostIp}:8000",
    "${hostIp}:5173"
) -join ','

if (-not $OutputPath) {
    $dockerDir = Resolve-Path (Join-Path $PSScriptRoot '..\docker')
    $OutputPath = Join-Path $dockerDir '.env.runtime'
}

if (-not $NoWrite) {
    $content = @(
        '# Generated by scripts\write-runtime-env.ps1. Local machine values only.',
        "MESOCO_HOST_IP=${hostIp}",
        "APP_URL=${appUrl}",
        "ASSET_URL=${appUrl}",
        "VITE_HMR_HOST=${hostIp}",
        "SANCTUM_STATEFUL_DOMAINS=${statefulDomains}",
        'SESSION_DOMAIN=(null)'
    )

    Set-Content -Path $OutputPath -Value $content -Encoding ASCII
}

Write-Host "Host IP:   ${hostIp}"
Write-Host "Backend:   ${appUrl}"
Write-Host "Frontend:  ${frontendUrl}"

if (-not $NoWrite) {
    Write-Host "Runtime env: ${OutputPath}"
}
